### PR TITLE
Added ability to register an element from its "class"

### PR DESCRIPTION
**Pull request by lgrignon**
Hello,

  Your API seemed very promising to us so we started to use it, but it lacks the possibility to declare the  polymer element with its class:
    
    class My extends polymer.Base implements polymer.Element {
    }

    createElement(My); // did not work for us

  So we slightly modified your API to enable this.

  Please tell us if you are ok with this, and please merge if so.

  Thanks for your work!

### CODE REVIEW

**Comment by nippur72** [comment]
Hi, thank your for your interest in PolymerTS. 

I would like to discuss your PR as I've not fully understood it. Can you please be more specific about why it did not work for you? Do you have an example?

The current API supports two alternate registering methods that should work:
- from element's .html file, have a `<script>` tag that calls `createElement(MyElement);`
- from typescript source code call `createElement(MyElement);` but only after the event `WebComponentsReady` has fired. 

Regarding your code:
```TypeScript
var polymerBaseInstance: polymer.Base = new polymer.Base();
```
`Polymer.Base` is not meant to be instantiated (it's an empty object), its purpose is only to enable type checking and intellisense in TypeScript. Actually it's a sort of hack because you can't use `interface` or `declare class` for this purpose. 

```TypeScript
var elementInstance: polymer.Element = new (<any>elementClass)();
```
why do you call element's constructor? If you need object initialization, you should instead implement `created()` or `ready()` in your element.

**Comment by lgrignon** [comment]
Hello again, 
  Thanks for answering quickly.

  I have to apologize, I should have explained more since this is not trivial.

  There were two problems behind createElement:
1) The element parameter type was polymer.Element, not Function, which as far as I know, does not allow to pass a class reference (MyInline for instance). It did not compile.
2) It only passes the prototype of element to the Polymer function, thus ignoring all the members (except methods) the developer could have defined. I think it is not a good thing because if we want an object oriented Polymer, we want to use object's properties :) (Without having to put a @property on it, of course)
Ex, I had something like: 
    
    class MyInline {
      private prop1: string;
    
      public created(): void {
        console.log(this.prop1); // prop1 is undefined
      }
    }
    
Regarding the second part of your feedback, the instantation of polymer.Base is actually a hack to not pass the properties and methods which are already defined by polymer to the Polymer function, the same goes for the element instantiation.

In this PR, the createElement method extracts all the useful members (including properties) in the element's class, and pass it to the Polymer function.

This may still be not clear, please ask me for anything.
Have a good evening.
Bye.

**Comment by nippur72** [comment]
Ok, got it, thanks! 

Everything originates from the fact you want to use field members without tagging them with the `@property` decorator. I understand the reasons behind that (more pure object-oriented, etc.), it makes sense. 

The actual pattern is to have `@property` on public fields, and to initialize private fields within `created()`, e.g.:
```typescript
class MyInline {
  private prop1: string;

  public created(): void {
    this.prop1 = "";
    console.log(this.prop1); // prop1 is no longer undefined
  }
}
```
But of course this is not elegant at all. 

I will ponder it a little more, I want to check how the problem is solved in PolymerDart (we're trying to make the two API somewhat aligned). 

Perhaps we can make `constructor()` work as a substitute for `created()`.

Regarding having `polymer.Element` in place of `Function`, it should compile as long as your class-element implements the interface `polymer.Element` (it's easy to forget it). Note that `polymer.Element` is an interface all made of optional members.

**Comment by nippur72** [comment]
Update: I'm struggling to make your PR work, perhaps there's something that I'm missing, can you please help me?

Because you have
```typescript
var flattenedComponent: any = {};
```
then your `flattenedComponent` doesn't have a `.prototype` (only Functions have it), and that causes 
```typescript
if ((<any> element.prototype).template !== undefined || (<any>element.prototype).style !== undefined) {
// and
Polymer(element.prototype);
```
to throw an error.

This is what I'm getting if I merge your PR (check the branch `register-alt`), so what I am missing? Can you please pull a PR with a simple working example?

I also suspect there is an issue arising from the fact that class constructor is called only once at the registration time, but due to the above error I was not able to verify it.

Anyway I have a possible solution for all this with a different implementation, but I would like to make your PR work as expected first.

**Comment by lgrignon** [comment]
Thanks again for your reply. That makes sense to me.
Using the constructor along with the created could be great!

Just to clarify, the problem I had with my element registration was a bit tricky, now it works with createElement(el: polymer.Element):
```javascript
interface A {
    prototype?: Object;
}

function a(param: A): void {
}

class Parent implements A {
    prop1: number;
}

class Foo implements A {
    prop2: string;
}

a(B); // Typescript complains about Foo not having an indexer [key: string]: any due to interface A declaring prototype
```
I fixed it by declaring a fake indexer, but I don't understand why Typescript is not aware that every object have an indexer. Perhaps polymer.Base could define [key: string]: any to avoid this weird problem although it is more a TS problem. (I think I remember have seen a discussion about this on the TS forums).

**Comment by lgrignon** [comment]
Oh, I just saw your second answer.

Indeed, the first commit was buggy but there is a second commit, I don't know if you have it?

https://github.com/lgrignon/PolymerTS/commit/ae9a503e524a41b72b27be5a0e6efa104e0c63cb

**Comment by nippur72** [comment]
Oops looks like I've missed your last commit :sad: 

Now I'm testing it on the branch `lgrignon`. Will be back with some comments soon.

**Comment by nippur72** [comment]
Ok, it happens just what I suspected.

Look at the `lgrignon` branch, I've added a failing case for the MyInline element:
```typescript
class MyInline extends polymer.Base implements polymer.Element {
   private myprivate = [1,2,3];

   ready() {
      if (this.myprivate[0] == 1) {
         console.log("correct value preserved");
         this.myprivate[0] = 5; // unfortunately this writes in all instances of the element        
      } else {
         console.log("correct value NOT preserved");   
         console.log(this.myprivate);
      }
   }
}
```
if you run it with 2 separate instances of `<my-inline>` it will fail on the second. This because `myprivate` array is actually the same object across all instances of the element, which is not what it's meant to be. 

This happens because the constructor of the class is called at registration time instead of being called at element instantiation time.

I think I have a fix for it, but it requires a different approach.

**Comment by lgrignon** [comment]
Damned, I wasn't sure about it and didn't take time to test.

Maybe we could store the initial value of the fields and generically clone it when element is created - under the hood of course -.

**Comment by nippur72** [comment]
I already have a working fix, but I want to make sure it doesn't have side effects. Also I want to integrate with Polymer's factory constructors if possible.

**Comment by lgrignon** [comment]
:+1:

**Comment by nippur72** [comment]
Ok, I pulled the fix on the `master` branch, if you want to test it you can bower the latest release. 

I started from the old code (the one with `.prototype`) because it fitted better. 

The fix consists simply of applying (`.apply()`) class constructor directly on the polymer element, so that all initialization are done directly on it. So no need to clone or do other tricks. 

The actual `apply()` is delayed to the `created` event, and if there's already a created event defined, it's linked after the constructor call. 

I hope there are no side effects.

**Comment by lgrignon** [comment]
Hello again :)
Looking at the code, the fix seems ok, but it requires the developer to use the component annotation which should be, I think, optional (as would be the @property annotation with our latest evolution).
That was the reason why I put it in createElement and not in the component definition. Don't you think it would be better? 
In addition, I do not see the code responsible for keeping the members outside the prototype and without @property but maybe you plan to do it after.

Unfortunately I can't test your annotation because I'm stuck with TS 1.4 but if you can answer the 2 points above, it would be great.

**Comment by nippur72** [comment]
Private members do not require annotations, but yes polymer-published properties do still require them.

I'm not totally sure about having properties published automatically without the decorator. Consider also that apart from simple cases, the decorator is needed (type, notify etc).

As for what actaully puts field members outside of the prototype, it's the constructor itself. When constructor is called with `apply` it initializes all field members and thus it injects them onto the object.

**Comment by lgrignon** [comment]
Yes, totally agree for polymer published properties. But I was talking about the @component annotation and the fact that your constructor fix won't be available while using only createElement and not @component. In our project, we only use createElement and define the "is" property in the element's class.

I think it is better to keep all the features available to any developer using createElement without using the @component annotation.

In the mean time, we keep using the fork. 
Please feel free to ask any additional question if you need.

**Comment by lgrignon** [comment]
To be perfectly clear: we are able to use your API without @component because we defined an "is" member on all our elements (not annotated with @property) and so this also works only because we modified createElement to take all the members :)

**Comment by nippur72** [comment]
Ok, clear, you want to use it without `@component`. I guess it's because you are still with TypeScript 1.4? Is there any particular reason you are not upgrading?

Anyway, I think we can cover your case too. I moved the constructor-patch routine out of the `@component` decorator, and I call it just before registering. So no need to use `@component`.

The only drawback is the global namespace having one more function named `patchConstructor()`. (I tried to incorporate it in the Polymer object as an extension, but alas, the Polymer ob is not available so early because of `<link rel="import">`).

Tell me if it works this way.

**Comment by lgrignon** [comment]
Shortly: It is easier to declare a component just by writing class My extends XX {} than to write an additional annotation. This is the main reason why we don't use it but also because we are not ready yet to move to TS 1.5 in production :)

Thank you for your work. I am preparing a little commit based on yours to support our case, which is the copy of the properties at registration, something simple. I create the PR within minutes.

NB, the case:
```javascript
class MyAbstract extends polymer.Base implements polymer.Element {
  //...
}

class My extends MyAbstract  {
  private myProp1: string = 'initialVal';
}

createElement(My); 
```

**Comment by lgrignon** [comment]
I am sorry but I won't create the PR for now because I am facing another problem and I would like your opinion about it.

I tried to keep your "prototype" way of thinking and added the ability to copy the initial properties values at created time but there was another problem. Indeed, while passing the prototype to Polymer, it does not retrieve the methods in the parent classes! This is very problematic for us since we have several helper methods in a parent class named AbstractElement.
That's why our way of only copying the properties of a fake instance of the class was convenient, a hack for sure, but

**Comment by nippur72** [comment]
I think we have a problem with inheritance, because we don't use `new`. Let's see if there's a workaround for this.

**Comment by lgrignon** [comment]
We could use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto

but I don't understand why you do not want to use the hack of the fake instance?

**Comment by nippur72** [comment]
the hack of the "fake instance" is not good because any array or object created within the constructor (or in property initialization) would be shared among all element instances; and the only workaround is to deep clone each property value, which I don't like (slow).

Regarding the last problem of broken inheritance, yes we could flatten recursively the object before its registration by looking at its `__proto__`. E.g this pseudo-code:.
```
function deflattenObject(ob) {
  ... ob.__proto__ ...
}

var flattened = deflattenObject(element.prototype);
Polymer(flattened);
```

but, other than being complex, `__proto__` is non-standard and it's suggested to not use in production.

I don't have any other idea for now, but if you come up with a good solution just send the PR and I'll comment it.

**Comment by lgrignon** [comment]
Hello, it's me again :)

I just committed a new version, mixing the prototype way and the ability to have 
1) plain old classes 
2) plain old properties
3) inheritance
4) identity segregation

If you look at the implementation, there is still the fake instance hack, but it is only used to build the full model prototype. Everything else is clear and only using prototype.

I am very satisfied with this solution and I think it won't break the existing annotations. 
I performed several tests without the annotations and everything seems alright.

Please tell me if your tests pass and if you think it's a good solution.

NB: the value are copied at creation via natural js copy so primitive values are copied and references are kept which I think is the correct behavior for us. Then your constructor patch handles the rest of the initialization.

**Comment by lgrignon** [comment]
Wrong alert, the problem of the array remains the same. We have to figure out how to reinitialize properties. I'm working on it again.

**Comment by lgrignon** [comment]
OK, Now it works, radical strategy change. This approach is more similar to the first I proposed but works in all cases. The process:
1) we create an instance of the polymer.Element corresponding to the registered element. This instance is dedicated to the Polymer registration, this is our model which should be invariant.
2) we override "created" to instantiate a new instance of our element. This will initialize perfectly the instance we requested, but this instance is only temporary. Then we copy all the "not polymer" members of the temporary element to the actual element being created (but not instantiated because polymer doesn't do that)

This solution is fast and answers all of our constraints.

The tradeoff is that we have to modify slightly your annotations but I'm not sure about that. I will try to use the annotations with this new version and keep you informed with the results.

Thanks again for your patience.

**Comment by lgrignon** [comment]
The @component annotation is still working with my modifications, good news :)

**Comment by achirac** [comment]
sorry for this pollution of commits but some collegues had to merge and accidentally pushed

**Comment by nippur72** [comment]
I've been studying your last changes, and I think the "dedicated instance" (step 1) is not required after all. It's enough to copy members from the prototype and later add all full members during the real instantiation.

Please check the branch `test-registration` where I've merged your code and modified as above.

Look also for the `MyInline` element example that is now an extension of `MyAbstract` (to see if inheritance works).

**Comment by lgrignon** [comment]
Everything seems ok to me except you didn't regenerate the js file.

**Comment by nippur72** [comment]
I just realized that if you don't make the "dedicated instance", your use case is broken, because the `is:` is left out of the prototype.

But at least your solution solves the problem of inheritance. 

What I don't like of the "dedicated instance" is that it might cause problems with singleton elements.

**Comment by lgrignon** [comment]
I don't understand. Singleton are not supported in Polymer, right? And I think it would be a problem to have a singleton class as a polymer element, since it should be instantiated once per use.

Maybe I got it wrong?

**Comment by nippur72** [comment]
Singleton in the sense of "element instantiated only once". 

Take for example a sort of "storage" component: if you allocate resources on the `constructor()` then your resources will be allocated twice, because of the double call of the constructor.

Anyway I made another commit on the `test-registration` branch that cover also your use case. 

Now:
* if the `is` property is defined on the prototype, then it's assumed you are using decorators, so don't instantiate twice, just copy from the prototype.
* if the `is` property is undefined, then assume no decorators used, and make a dedicated instance so that `is` and other properties are accessible.

What do you think?

**Comment by lgrignon** [comment]
For the resource problem, I think every developer should be aware that his component is going to be instantiated once for each instance (normal case). This is the perfect example to explain why we should never put low-level logic in UI components :)

That said, I think your proposal with 2 scenarios is too ambiguous, I am not sure the developers using the API would understand why there is two behaviors, don't you think?

**Comment by nippur72** [comment]
Since supporting the two scenarios is rather cheap (it's just an `if` statement) I think we can afford it.

Sure it's a bit ambiguous, but those who use decorators don't have to care or know about it, it just works as before, with no payloads and with the added benefit of working inheritance.

Those who don't use decorators will have to pay the extra instantiation and be aware of that, but since it's unavoidable it's ok for me.

So I am oriented to merge this last version, is there anything else we should take into account?

**Comment by lgrignon** [comment]
Ok, I still think it could stay as it was in my PR but it's your call ;) (I keep thinking that because in my opinion, the overhead due to the instantiation of a plain js object is trivial compared to the load brought by polymer itself. But again, I will follow your decision, you are the author :)

Another detail (which may not be such insignificant), we did further tests this afternoon and sadly, there is another problem assigning new properties during created. Polymer listens to properties modifications and triggers internal and external events when modified. The problem is that those listeners rely on the fact that the element is fully initialized at created, but it's not the case here because we are just assigning all the default properties. I think it could be possible to disable temporarily the properties change tracking, but I've to figure out how to do that.

I will get back to you once I know how to do. I recommand you not to merge this PR until this problem is solved.

Thanks again.
Bye

**Comment by nippur72** [comment]
Can you please provide an example of such faulty initialization? I would like to reproduce the behavior.

I don't think it's possible to disable change tracking, because Polymer relies on custom setters rather than Object.observe to detect changes. But perhaps there is a global switch.

**Comment by lgrignon** [comment]
To reproduce this failure, declare a plain old property in your element, mine is:
```javascript
public year: number;
```
and use it in a data-binding, like this:
```html
<paper-input value="{{year}}"></paper-input>
```
I am currently looking for a workaround and I think I have something.

I will keep you informed.

**Comment by nippur72** [comment]
I think I've found something.

We are assuming we can access properties during `created()`, but in reality that is not the case. It was possible to do so in 0.5 (for initializing the props) but looks like this is no longer possible in 1.0. 

From the docs:

created - Called from createdCallback immediately after the element is created, before its template has been stamped. **Note that properties with side-effects (bindings, observers, computed property dependencies) must not be accessed during created.** In general, most lifecycle work should be performed in one of the other callbacks below.

So I think it will be enough to move our initialization in another event (`ready` or `attached`).

**Comment by nippur72** [comment]
look at `test-registration` branch, I moved the constructor call from `created()` to `ready()` and it seems to work.

**Comment by lgrignon** [comment]
Yes, that's a good idea but will polymer be aware about plain properties if neither the "dedicated instance" nor the element has those properties at creation time?

I'll try in a few minutes.

**Comment by lgrignon** [comment]
It seems to work like a charm! Well done! (Due to the if you added on the 'is' being present on the prototype)

If it's ok for you, let's merge this :)

**Comment by nippur72** [comment]
Ok, I've merged it and released as 0.1.0. 

Thank you very much for your precious help.

**Comment by nippur72** [comment]
Update:

as I was working to implement `factoryImpl()`, I realized that the best place where to put our constructor-call is indeed within `factoryImpl()` and no within the `ready` event. (As a side note, `ready` is not available in polymer-mini/micro). 

FactoryImpl is called by Polymer after `ready` but before `attached`.

So, not only I moved the constructor, but I also gave the ability to call it with parameters. That means that now the `constructor()` is a replacement for `factoryImpl()`. 

Example:
```TypeScript
@component("my-info")
class MyInfo extends polymer.Base implements polymer.Element
{
   private someInfo: string;

   constructor(someInfo: string) {
      this.someInfo = someInfo;
   }
}

// createElement returns the constructor for the element
var myInfo = createElement(MyInfo);

// so we can create it
var el = <any> new myInfo("hello world");

// and attach in some way to the DOM
document.body.appendChild(el);
```

I still have to find a way to avoid the cast to `<any>`, I struggled a bit with generics but haven't found a solution.

P.s. look at the `factory` branch

**Comment by nippur72** [comment]
forget, there is a big flaw.

**Comment by nippur72** [comment]
Ok, I think I managed to fix it. It's a bit complex, but seems to work. 

Now:

- if no-parameter constructor is used, initialization is done in `attached`
- if with-parameter constructor is used, `factoryImpl` saves the arguments and later `attached` does the initialization.

So in the end initialization is always done in `attached`, with the difference that it can have arguments.

I had also to fix a bug with `@computed` that we introduced with the new initialization strategy.

One more note: I moved `implements polymer.Element` within the `polymer.Base` so it's shorter to declare an element.

**Comment by lgrignon** [comment]
Good idea to move implements polymer.Element to polymer.Base

About the typing of createElement, I would do:
```javascript
 function createElement<T extends polymer.Element>(elementType: new (...args: any[]) => T): new (...args: any[]) => T {
        // ...
    }
  
   var homeViewFactory: new (year: number) => HomeView = createElement(HomeView);
    
   var homeView: HomeView = new homeViewFactory(2015);
```
However, I'm not convinced initializing the element in the attached event is a good idea. Indeed, most of the developers will think (and they're right) that the element is fully initialized when the ready event fires, but it won't be true in our case. Am I missing something? Isn't it possible to call our initialization 
in factoryImpl, whether constructor has arguments or not? Or couldn't we use the ready event if available, and factoryImpl if not?

**Comment by nippur72** [comment]
ok, thanks for the function signature, I will add it. Anyway it does not fix it completely, because it doesn't check arguments in the `new`. E.g.
```TypeScript
// ...
constructor(a: string) {} 
//...
var homeView = new homeViewFactory(2015,"foo","bar"); // it doesn't check arguments
```
Regarding  "where to put initialization", it's a bit complex I'll try to explain it the best I can.

In my opinion (I might be wrong, tell me) it's not correct to assume the element is fully initialized in `ready`. This because the Polymer library itself calls `factoryImpl` *after* the `ready` event. So if you have an element with a custom constructor, it won't be fully initialized in `ready`.

So I assumed the correct place for "fully initialized" is either `factoryImpl` or `attached`.

Ideal place would be `factoryImpl` but unfortunately it doesn't get called during a "normal" instantiation. The only function that gets called in both cases is `attached`. 

So my solution is:
- move our fake initialization in `attached`
- use `factoryImpl` to save `constructor()` arguments that will be later used in `attached` 

It's a bit crippled but I don't see a better solution.

**Comment by nippur72** [comment]
Forgot to tell that an alternative is to drop the custom constructor feature and revert back to:
- constructor() with no parameters in class definition
- factoryImpl(args) function in class

Tell me what do you think of it

**Comment by lgrignon** [comment]
Hello again.

I think you're right, we haven't any other choice than to abstract the constructor support in either factoryImpl or attached.

For the createElement signature, I did not found a solution to check arguments number and type :(

**Comment by nippur72** [comment]
Regarding the correct order, I've opened an issue in [polymer](https://github.com/Polymer/polymer/issues/2075), let's see what they'll say.

**Comment by nippur72** [comment]
Found another issue! (unit testing is starting to give results...)

The problem is that when we make our "fake" instance, within the `constructor()` the object `this` points to the typescript object, not to the polymer element. This means that  in the constructor you can't call anything that is polymer-related, e.g. `this.fire()`.

But I think I've already found a solution that I would like you to check it if possible. Look at the `simulated-new` branch. 

To sum up, currently we do:
- create a class instance with `new`
- copy everything from instance to polymer element object

But why not modify this into:
- create an instance of the class without applying the costructor (members are there but properties are uninitialized)
- copy everything from instance to polymer element object
- apply the class constructor *on the polymer element object* rather than class instance

This way, `this` is correctly referenced to a fully initialized and consistent object. Makes a lot more sense to me, don't you think? Also this lets me avoid a patch for the `@computed` decorator.

I had this idea while looking at how `new` can be simulated in JavaScript:
```TypeScript
function SimulatedNew(fn: Function, argArray: IArguments) {
   var newObj=Object.create(fn.prototype);
   fn.apply(newObj, argArray);
   return newObj;
}
```
So our new fake instantiation (well... no longer fake!) is
```TypeScript
   registeredElement["$custom_cons"] = function() {
      // reads arguments coming from factoryImpl
      var args = this.$custom_cons_args;      

      // copies members from instance to polymer element (this)
      var elementInstance = Object.create(elementClass.prototype);     
      for(var propertyKey in elementInstance) {         
         // do not include polymer functions
         if(!(propertyKey in polymerBaseInstance)) {            
            this[propertyKey] = elementInstance[propertyKey];
         }
      }      

      // applies class constructor on the polymer element (this)
      elementClass.apply(this, args);
   };
```

**Comment by lgrignon** [comment]
Seems perfect to me.

**Comment by nippur72** [comment]
Ok, I merge then, thank you for giving a look at it. 

P.S. now element's factory is also available as `MyClass.create(args)` which is very convenient (it's a static method).

**Comment by nippur72** [comment]
Another update: maybe I've found a way to avoid all this altogether and let Polymer handle es6 classes directly. Have a look at [this issue](https://github.com/Polymer/polymer/issues/2067).

**Comment by nippur72** [comment]
I've finished to implement this feature, now there are no object cloning or property coping or fake instances.

The object `polymer.Base` is no longer a dummy object but is seen as a `declared class` to extend. The code is a lot much cleaner and (I guess) faster too.

Could you please check your use case scenario (TS1.4) ? I had to manually cover it. Refer to `master` branch.

**Comment by lgrignon** [comment]
Hey, I am sorry I had only a few time but I will try soon.

Many thanks.

**Pull request closed without merging**
