### PR TITLE
inherited members are carried to prototype

### PR DESCRIPTION
**Pull request by lgrignon**
et voilà :) Tested with multiple instances of the component on the page.

### CODE REVIEW

**Comment by nippur72** [comment]
Ok, but this fixes only the "backward TS 1.4 compatibility" case, right?

**Comment by lgrignon** [comment]
Yes, you are right but I did not want to interfer with the other mode because I thought it would bother you.

If you want, I could prepare something working for the normal case as well.

**Comment by nippur72** [comment]
Ok thanks! As long as no extra instance is created I think it will be fine.

The problem with the extra instance is that you never know what's is in the constructor, so there's risk of things gets called or initialized twice.

I would try copying methods from `__proto__`, but I have to think better over it.

**Comment by lgrignon** [comment]
Yes, I understand. But the main problem with this __proto__ approach is that you still need to declare all the properties in the constructor, you cannot declare them as plain old javascript properties.

That's why I still use the 1.4 version after all, because I want all my instance properties copied.
I don't know how to achieve this with the proto way and I think there is no way.

That being said, my opinion is that the constructor should do nothing too complex, it would look like an anti pattern to me but that is only my thoughts :)

Please tell me if you chose to integrate this fix for the "instance" way. I will keep going on this version.

**Comment by nippur72** [comment]
yes this fix can be merged even if it's only for the "instance" case. Better if we came with a common solution. More on this tomorrow after I think about it.

**Comment by lgrignon** [comment]
Perfect.

Thanks again.

Have a nice evening.

**Comment by nippur72** [comment]
I think I've found a way using `__proto__` that does not require copying or looping through members, and also should work in both cases. 

It's only a bit complex (for me) to understand as I'm not very acquainted with JavaScript's prototype inheritance model.

Anyway once I have something working I'll push it in a separate branch for you to look at.

**Comment by lgrignon** [comment]
Maybe you could point me out the trick you found so I could write it for you, saving a little bit of your time. So you could directly integrate this PR.
Let me know.
Bye.

**Comment by nippur72** [comment]
The standard Polymer element is a long chain starting from `HTMLElement` and ending with `.__proto__ = null`.

The trick was to attach there, on the last node, the tail of the chain from our typescript class (starting from class's super).

It was a bit complicate (due to a circular reference issue), so I've dropped it for a far more easy solution.

What I do now is to copy from `__proto__` recursively. Usually there are few members, so it should be quite fast:

```TypeScript
      function copyMembers(dest: Object, source)
      {
         if(source===undefined || source===null) return;
         Object.keys(source).map((member)=>
         {           
            // copy only if has not been defined
            if(!dest.hasOwnProperty(member)) dest[member] = source[member];
         });
         copyMembers(dest, source.__proto__);   // <-- goes recursively
      }
```

Since this fix cover both cases, I've rolled back your previous PR. 

This patch is in the `inheritance` branch for you to look at. Once you say it's ok, I'll merge to `master` and make a new rel.

P.S. I've also added a test case for more than 1-level of inheritance.

**Comment by lgrignon** [comment]
I think this does not cover the copy of the inherited instance fields. I actually think there is no way to achieve it without instantiating the

**Comment by nippur72** [comment]
Luckily for us, instance fields are created in the constructor by TypeScript, so we get them "for free", so no need to worry about that. 

Indeed in PolymerTS we have `elementClass.apply(this, args)` expressily for calling the constructor and rebuild the properties of the class.

To make this more evident, consider the following code:
```TypeScript
class X
{
   public myfield = 42;
}
```
which is transpiled into:
```Javascript
    function X() {
        this.myfield = 42;   // <- here we are within the constructor
    }
```
And if a property is not initialized, it will be `undefined` which is ok too.

This trick of course doesn't work for methods because they are put in the `.prototype` and that's why inheritance was broken.

**Comment by lgrignon** [comment]
Oh yeah, you are totally right I forgot this obvious detail.

Please let me know when your fix is published on bower and I will try it out on our projects.

Thanks.

**Comment by nippur72** [comment]
Ok, it's released as `0.1.16`. Let me know if something goes wrong.

**Pull request merged**
