### PR TITLE
Support for constructor, class inheritance, decoratorless syntax

### PR DESCRIPTION
**Pull request by nippur72**

### CODE REVIEW

**Comment by nippur72** [comment]
many thanks to @lgrignon

**Comment by lgrignon** [comment]
Good job :)

:+1:

**Comment by lgrignon** [comment]
One last question (I promise ;)). How do you launch your test within the Test directory? Do you launch manually the compilation and try into your browser?
We could try to make it more standard with jasmine / phantomjs and travis if you want.

**Comment by nippur72** [comment]
I launch the test project from the Visual Studio IDE (2015 Community Edition).

It's not exactly a test, it's more like a blank sheet where I run quick experiments, just to see if something works or not.

But for sure, we absolutely need tests. I was thinking of borrowing the ones from PolymerDart, at least to see how they are implemented (this because testing DOM / UI is much harder than plain unit testing).

Feel free to add a real test projected. Jasmine is my fav too.

**Comment by nippur72** [comment]
I've added Jasmine to the "Test" project and split it into "Sample" and "Test".

Will start writing some. Using console, panthomjs and a thing called "Chutzpah" (for now).

**Comment by lgrignon** [comment]
Cool, thanks. I will take a look at it.

**Pull request merged**
